#!/bin/sh

# This script should only run if we're in a Docker container.
if [ ! -f /.dockerenv ] ; then
    echo "This script can only be run in a Docker container."
    exit 1
fi

cat<<EOF >> ~/.gdbinit
add-auto-load-safe-path /writ/.gdbinit
EOF

eval `resize`

cd /writ
gdb "$@"

