record bar {
    name: string,
    age: s32
}

record deep-bar {
  id: s32,
  x: bar
}

record deeper-bar {
  id: s32,
  x: deep-bar
}

record foo {
  movies: list<string>,
  code: list<s32>,
  bars: list<bar>,
  b: list<bool>
}

construct-bar: func(name: string, age: s32) -> bar
test-record: func(a: bar) -> s32
test-deep-record: func(a: deep-bar) -> s32
test-deeper-record: func(a: deeper-bar) -> s32
bar: func(a: bar) -> bar
deep-bar: func(a: bar) -> deep-bar
deeper-bar: func(a: bar) -> deeper-bar
rev-deeper-bar: func(a: deeper-bar) -> deeper-bar

foo: func() -> foo
test-foo: func(a: foo) -> foo
